version: '2.2'

x-es_instance: &_es_instance
    image: docker.elastic.co/elasticsearch/elasticsearch:$ES_VERSION
    mem_limit: $ES_MAX_MEM
    ulimits:
        nofile:
            soft: 65535
            hard: 65535
        memlock:
            soft: -1
            hard: -1
    networks:
        - arkime-elastic


services:
    es01:
        <<: *_es_instance
        container_name: $ES_NODE1
        environment:
            - node.name=$ES_NODE1
            - discovery.type=single-node
            - cluster.name=es-arkime-cluster
            - bootstrap.memory_lock=true
        volumes:
            - $ES_DATA_DIR/$ES_NODE1:/usr/share/elasticsearch/data
    arkime:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - $ES_NODE1
        environment:
            - ES_HOST=$ES_NODE1
            - ES_PORT=9200
        ports:
            - $ARKIME_PORT:8005
        volumes:
            - arkime_config:/data/config
            - arkime_logs:/data/logs
            - $PCAP_DIR:/data/pcap
        networks:
            - arkime-elastic

volumes:
    arkime_config:
    arkime_logs:


networks:
    arkime-elastic:
